# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5d6dce3478155dcd28573a869d077c1ff8a4825f690b3cdbb0c77231ebbcc3a2cc911a2ea33177c6529921d8aa097686214fb819b88dcda5704c74d980be72a6

test:
  secret_key_base: 5be8ab768088f45a466074f4d2152bef77ab92c868bb75f56212d3c39f397c191221d9f8de7d377217b7a9e5c48780be59f0d1e3632161f35033d595b8008b66

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
